### PR TITLE
Remove logging

### PR DESCRIPTION
**Pull request by JayZhouzzj**

### CODE REVIEW

**Comment by lasanthafdo** [comment]
Any specific reason for removing logging? I thought having these kinds of logs are beneficial overall to understand what the script is doing.

**Comment by JayZhouzzj** [comment]
I added the logging before to log the numerical values. But now I think the values are already shown in the graphs. Also the code changed. These logging have error now

**Comment by lasanthafdo** [comment]
> I added the logging before to log the numerical values. But now I think the values are already shown in the graphs. Also the code changed. These logging have error now

The logs have an added benefit of allowing you to double check the values displayed in the graphs. This can help us debug if there is an issue in the graph generation. Even if you have these numbers on the graph, if you want add these numbers to a report, it is easier to copy it from the console log than typing the number by looking it at the graph.

Ideally, if there is an error in the logging code, it would have been better to fix the error. But if you think simply removing the logging is better, will accept the PR. Please let me know.

**Comment by JayZhouzzj** [comment]
I see. Makes sense thanks. I fixed it now

**Comment by lasanthafdo** [comment]
Thanks a lot for the PR!

**Pull request merged**
